/*
 * Ski Ride API for Distributed Computing
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for COEN6317 Project
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
